<a href="https://colab.research.google.com/github/myroslava-martyniuk/Martyniuk_Assignments/blob/main/9_1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [2]:
# Do not edit this cell

import numpy as np
import pandas as pd

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [3]:
res = np.array([1, 2, 3, 4, 5])

print(res)

[1 2 3 4 5]


In [6]:
res2 = np.arange(1,6)

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [10]:
res3 = np.array(np.random.randint(1, 101, size = (3,5)))


print(res3)

[[48 11 27  4 72]
 [81 69 38 92 31]
 [65 54 18 92 48]]


### Task 3

Print the first row of array `res3`.

In [13]:
row1 = res3[:1, :6]
print(row1)

[[48 11 27  4 72]]


### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [15]:
lastcol = res3[:, -1]
print(lastcol)

[72 31 48]


### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [18]:
# Min
second_col = res3[:, 1]
print(second_col)
res_min = np.min(second_col)

print('min =', res_min)

[11 69 54]
min = 11


In [19]:
# Max
res_max = np.max(second_col)

print('max =', res_max)

max = 69


In [20]:
# Sum
res_sum = np.sum(second_col)

print('sum =', res_sum)

sum = 134


### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [27]:
def f(x):
  return np.exp(2 * x)


start = 0
end = 0.5
step = 0.1

valuex = np.arange(start, end + step, step)
valuey = f(valuex)


print("x  f(x)")
for i in range(len(valuex)):
  print(f"{valuex[i]}  {valuey[i]}")

x = 0.5
f_x = f(x)
print(f_x)

x  f(x)
0.0  1.0
0.1  1.2214027581601699
0.2  1.4918246976412703
0.30000000000000004  1.822118800390509
0.4  2.225540928492468
0.5  2.718281828459045
2.718281828459045


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [42]:
url = 'https://web.stanford.edu/class/cs102/datasets/Titanic.csv'
df = pd.read_csv(url)

### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [43]:
print(df.columns)

Index(['last', 'first', 'gender', 'age', 'class', 'fare', 'embarked',
       'survived'],
      dtype='object')


In [44]:
print(df.head(10))

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  So

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [45]:
df["full name"] = df["first"].str.cat(df["last"], sep=" ")
print(df.head(10))

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  \
0   7.2500  Southampton       no   
1  71.2833    Cherbourg      yes   
2   7.9250 

### Task 10

Remove the two original columns - last, first.

In [46]:
del df['last']
del df['first']
print(df.head(10))

  gender   age  class     fare     embarked survived  \
0      M  22.0      3   7.2500  Southampton       no   
1      F  38.0      1  71.2833    Cherbourg      yes   
2      F  26.0      3   7.9250  Southampton      yes   
3      F  35.0      1  53.1000  Southampton      yes   
4      M  35.0      3   8.0500  Southampton       no   
5      M   NaN      3   8.4583   Queenstown       no   
6      M  54.0      1  51.8625  Southampton       no   
7      M   2.0      3  21.0750  Southampton       no   
8      F  27.0      3  11.1333  Southampton      yes   
9      F  14.0      2  30.0708    Cherbourg      yes   

                                           full name  
0                             Mr. Owen Harris Braund  
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  
2                               Miss Laina Heikkinen  
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  
4                            Mr. William Henry Allen  
5                                    Mr. James Moran 

### Task 11

Calculate the total number of survivors in the dataset.

In [54]:
survived = df[df["survived"] == 'yes']
number_of_survivors = survived.shape[0]
print(number_of_survivors)


891
